---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Deploy nginx config file
      copy: src=../nginx/nginx.conf dest=/etc/nginx/nginx.conf
      notify: restart nginx

    - name: Deploy nginx site config files
      synchronize: src=../nginx/conf.d dest=/etc/nginx delete=yes recursive=yes
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
